
DROP TABLE ENROLMENT;
DROP TABLE STUDENT;
DROP TABLE SUBJECT;


CREATE TABLE STUDENT (
    STUDENT_NO NUMBER NOT NULL,
    SRUDENT_NAME VARCHAR2(10 BYTE),
    STUDENT_AGE NUMBER,
    CONSTRAINT PK_STUDENT PRIMARY KEY(STUDENT_NO)
);
 
CREATE TABLE SUBJECT (
    SUBJECT_CODE NUMBER NOT NULL,
    SUBJECT_NAME VARCHAR2(10 BYTE),
    SUBJECT_TEACHER VARCHAR2(10 BYTE),
    CONSTRAINT PK_SUBJECT PRIMARY KEY(SUBJECT_CODE)
);    
    

CREATE TABLE ENROLMENT (
    ENROLMENT_NO NUMBER NOT NULL,
    STUDENT_NO NUMBER,
    SUBJECT_CODE NUMBER,
    CONSTRAINT PK_ENROLMENT PRIMARY KEY(ENROLMENT_NO),
    CONSTRAINT FK_ENROLMENT_STUDENT FOREIGN KEY(STUDENT_NO) REFERENCES STUDENT(STUDENT_NO),
    CONSTRAINT FK_ENROLMENT_SUBJECT FOREIGN KEY(SUBJECT_CODE) REFERENCES SUBJECT(SUBJECT_CODE)
    
 );       
