/*
    KEY 제약조건 변경하기(굳이 쿼리문안에 포함 할 필요없이 따로 부여해줄 수 있다.)
    1. 기본키
        1) 추가
            ALTER TABLE 테이블명 ADD CONSTRAINT 제약조건명 PRIMARY KEY(칼럼);
        2) 삭제
            ALTER TABLE 테이블명 DROP PRIMARY KEY;
            ALTER TABLE 테이블명 DROP CONSTRAINT 제약조건명;
    2. 외래키
        1) 추가
            ALTER TABLE 테이블명 ADD CONSTRAINT 제약조건명 FOREIGN KEY(칼럼) REFERENCES 부모테이블(참조칼럼) [옵션]
        2) 삭제
            ALTER TABLE 테이블명 DROP CONSTRAINT 제약조건명;
*/

DROP TABLE SCHEDULE_TBL;
DROP TABLE PLAYER_TBL;
DROP TABLE EVENT_TBL;
DROP TABLE NATION_TBL;

CREATE TABLE NATION_TBL (
    N_CODE          NUMBER(3)         NOT NULL,
    N_NAME          VARCHAR2(30 BYTE) NOT NULL,
    N_PARTI_PERSON  NUMBER CHECK(N_PARTI_PERSON >= 0),
    N_PARTI_EVENT   NUMBER,
    N_PREV_RANK     NUMBER,
    N_CURR_RANK     NUMBER
    );
    
CREATE TABLE EVENT_TBL (
    E_CODE        NUMBER            NOT NULL,
    E_NAME        VARCHAR2(30 BYTE) NOT NULL,
    E_FIRST_YEAR  NUMBER(4),
    E_INFO        VARCHAR2(100 BYTE)
    );
    
CREATE TABLE PLAYER_TBL (
    P_CODE NUMBER(3)         NOT NULL,
    P_NAME VARCHAR2(30 BYTE) NOT NULL,
    N_CODE NUMBER(3)         NOT NULL,
    E_CODE NUMBER            NOT NULL,
    P_RANK NUMBER,
    P_AGE  NUMBER(3)
    );
    
CREATE TABLE SCHEDULE_TBL (
    S_NO         NUMBER(3) NOT NULL,
    N_CODE       NUMBER(3),
    E_CODE       NUMBER,
    S_START_DATE DATE,
    S_END_DATE   DATE,
    S_INFO       VARCHAR2(100 BYTE)
    );
    
-- 기본키 제거하기(쓸 일이 없음 쿼리문 자체를 삭제하는 코드가 위에있어서 전체 삭제 될텐데 굳이 코드를 따로 짜서 삭제 할 필요는 거의 없다,
--                 문법 소개일 뿐, 실제로 작성할 필요는 없습니다. DROP TABLE을 수행하면 제약조건도 모두 제거됩니다.)  
ALTER TABLE NATION_TBL 
    DROP PRIMARY KEY; --테이블의 기본키는 오직 1개이므로 제약조건 이름을 몰라도 삭제할 수 있다.
/*
    ALTER TABLE NATION_TBL
        DROP CONSTRAINT PK_NATION; --이거보단 위에가 더 추천
*/    
ALTER TABLE EVENT_TB
    DROP PRIMARY KEY;
ALTER TABLE PLAYER_TBL
    DROP PRIMARY KEY; 
ALTER TABLE SCHEDULE_TBL
    DROP PRIMARY KEY; 
    
-- 기본키 추가하기
ALTER TABLE NATION_TBL
    ADD CONSTRAINT PK_NATION 
        PRIMARY KEY(N_CODE);
ALTER TABLE EVENT_TBL
    ADD CONSTRAINT PK_EVENT 
        PRIMARY KEY(E_CODE);
ALTER TABLE PLAYER_TBL
    ADD CONSTRAINT PK_PLAYER 
        PRIMARY KEY(P_CODE);
ALTER TABLE SCHEDULE_TBL
    ADD CONSTRAINT PK_SCHEDULE 
        PRIMARY KEY(S_NO);
-- 외래키 제거하기
ALTER TABLE PLAYER_TBL
    DROP CONSTRAINT FK_PLAYER_NATION;
ALTER TABLE PLAYER_TBL
    DROP CONSTRAINT FK_PLAYER_EVENT;
ALTER TABLE SCHEDULE_TBL
    DROP CONSTRAINT FK_SCHEDULE_NATION;
ALTER TABLE SCHEDULE_TBL
    DROP CONSTRAINT FK_SCHEDULE_EVENT;    
-- 외래키 추가하기
ALTER TABLE PLAYER_TBL
    ADD CONSTRAINT FK_PLAYER_NATION
        FOREIGN KEY(N_CODE)
            REFERENCES NATION_TBL(N_CODE)
                ON DELETE CASCADE;
ALTER TABLE PLAYER_TBL
    ADD CONSTRAINT FK_PLAYER_EVENT
        FOREIGN KEY(E_CODE)
            REFERENCES NATION_TBL(E_CODE)
                ON DELETE CASCADE;    
ALTER TABLE SCHEDULE_TBL
    ADD CONSTRAINT FK_SCHEDULE_NATION
        FOREIGN KEY(N_CODE)
            REFERENCES NATION_TBL(N_CODE)
                ON DELETE SET NULL;   -- ON DELETE CASCADE도 가능하다 NULL이라고 무조건 ON DELETE SET NULL은 아니다.
ALTER TABLE SCHEDULE_TBL
    ADD CONSTRAINT FK_SCHEDULE_EVENT
        FOREIGN KEY(E_CODE)
            REFERENCES NATION_TBL(E_CODE)
                ON DELETE SET NULL;   -- ON DELETE CASCADE도 가능하다 NULL이라고 무조건 ON DELETE SET NULL은 아니다.                   
        
-- 연습. NATION_TBL의 기본키 제거하기  
-- 외래키(FK)에 의해서 참조 중인 기본키(PK)는 "반드시" 왜래키를 먼저 삭제해야 한다.
ALTER TABLE PLAYER_TBL
    DROP CONSTRAINT FK_PLAYER_NATION;
ALTER TABLE SCHEDULE_TBL
    DROP CONSTRAINT FK_SCHEDULE_NATION;
ALTER TABLE NATION_TBL
    DROP PRIMARY KEY;

-- 외래키 제약 조건 일시중지(비활성화) 
ALTER TABLE PLAYER_TBL
    DISABLE CONSTRAINT FK_PLAYER_EVENT; --부모키에 데이터가 없어도 입력이 허용된다(잠시 중지 시키고 나중에 관련 내용을 입력한다)

-- 외래키 제약 조건 다시시작(활성화)
ALTER TABLE PLAYER_TBL
    ENABLE CONSTRAINT FK_PLAYER_EVENT;    