/*
    다대다(M:N) 관계
    1. 현실에서 빈번히 나타나지만 주의해야 하는 관계이다.
    2. 두 테이블을 다대다 관계로 직접 연결하는 것은 불가능하다.
    3. 두 테이블을 관계 맺어 줄 별도의 테이블이 추가로 필요하다.
    4. 다대다(M:N) 관계 1개는 일대다(1:M) 관계 2개로 만들 수 있다.
*/
-- 테이블 삭제(주의! 생성의 역순으로 삭제할 것!)
DROP TABLE ENROLMENT;
DROP TABLE STUDENT;
DROP TABLE SUBJECT;

/*
    참고. 테이블 삭제 순서를 무시하고 삭제할 수 있는 옵션이 있다.(아래는 생성 순서대로 삭제하기 예시)
    DROP TABLE STUDENT_TBL CASCADE CONSTRAINTS;
    DROP TABLE SUBJECT_TBL CASCADE CONSTRAINTS;
    DROP TABLE ENROLL_TBL CASCADE CONSTRAINTS;
    추천하는 것은 아니므로 알고 계시는 걸로 만족하기!
*/
-- 과목 테이블 생성
CREATE TABLE STUDENT (
    STUDENT_NO NUMBER NOT NULL,
    SRUDENT_NAME VARCHAR2(10 BYTE),
    STUDENT_AGE NUMBER,
    CONSTRAINT PK_STUDENT PRIMARY KEY(STUDENT_NO)
);
-- 수강신청 테이블 생성 
CREATE TABLE SUBJECT (
    SUBJECT_CODE NUMBER NOT NULL,
    SUBJECT_NAME VARCHAR2(10 BYTE),
    SUBJECT_TEACHER VARCHAR2(10 BYTE),
    CONSTRAINT PK_SUBJECT PRIMARY KEY(SUBJECT_CODE)
);    
    
-- 수강신청 테이블 생성
CREATE TABLE ENROLMENT (
    ENROLMENT_NO NUMBER NOT NULL,
    STUDENT_NO NUMBER,
    SUBJECT_CODE NUMBER,
    CONSTRAINT PK_ENROLMENT PRIMARY KEY(ENROLMENT_NO),
    CONSTRAINT FK_ENROLMENT_STUDENT FOREIGN KEY(STUDENT_NO) REFERENCES STUDENT(STUDENT_NO) ON DELETE CASCADE,
    CONSTRAINT FK_ENROLMENT_SUBJECT FOREIGN KEY(SUBJECT_CODE) REFERENCES SUBJECT(SUBJECT_CODE) ON DELETE CASCADE
    
 );       
